name: Deploy

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build Project
        run: |
          npm install
          npm run build
      - name: Deploy to Linode
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME_STAGING }}
          password: ${{ secrets.SSH_PASSWORD_STAGING }}
          port: ${{ secrets.SSH_PORT_STAGING }}
          source: "./client/build,./client/package.json,./server/src,./server/package.json,./deploy.config.js,./package*.json"
          target: "/var/www/html/${{ secrets.SSH_FOLDER }}"
      - name: Run App
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_STAGING }}
          username: ${{ secrets.SSH_USERNAME_STAGING }}
          password: ${{ secrets.SSH_PASSWORD_STAGING }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.SSH_FOLDER }}
            npm install
            pm2 start deploy.config.js
